### ISSUE TITLE
Too prescriptive vimrc

### ISSUE THREAD

**Issue by JulianGindi** [istrategylabs/laptop#3]
I think the vimrc we chose to use is a bit too prescriptive. I think it's important for someone to be presented with "sensible defaults" (enough to be productive) when starting to use Vim or being presented with a new vim environment. A new vim user should learn the fundamentals of "unmodified vim" so they get a sense for what is consistently available across all vim environments. WIth that in mind, I recommend going for a lighter-weight vimrc such as Tim Pope's [vim-sensible](https://github.com/tpope/vim-sensible).

**Comment by JulianGindi** [comment]
[This](https://github.com/mhinz/vim-galore/blob/master/content/minimal-vimrc.vim) one is also very nice and well commented

**Comment by recursivefunk** [comment]
One could argue that including a vimrc at all is pretty prescriptive

**Comment by JulianGindi** [comment]
Vim and vimrcs are commonly added by default across many Unix-based systems. I think adding a very basic vimrc (like the one @jcarbaugh updated the repo with), is a perfectly reasonable idea.
